### ISSUE TITLE
Uso Firma Electronica

### ISSUE THREAD

**Issue by dmartinezbello** [jotraverso/firma-electronica#1]
Hola, Una consulta, puedo usar tu repositorio para completar un proyecto que estoy haciendo.
Necesito firmar un PDF y debe quedar en el mismo registro de las personas que lo firman y los certificados de seguridad deben quedar en el archivo.

**Comment by jotraverso** [comment]
Hola Daniel,

Claro que puedes consultarlo.

Si no recuerdo mal, cuando se firma el PDF queda la clave pública del firmante para que se pueda comprobar la firma, nunca puede quedar el certificado completo.

Gracias por tener en cuenta mi repositorio y un saludo.
